// Generated by CoffeeScript 1.11.1
(function() {
  var Client, Q, client, creds;

  Client = require('./client');

  Q = require('q');

  creds = function() {
    return {
      auth: Client.authStdin
    };
  };

  client = new Client();

  client.loglevel('debug');

  client.on('chat_message', function(ev) {
    return console.log(ev);
  });

  client.connect(creds).then(function() {
    console.log('yay!!');
    client.sendchatmessage('UgyFtnOAId3utgeMAP14AaABAQ', [[0, 'Hello World']]);
    return console.log('new conv.', client.getconversation('UgyFtnOAId3utgeMAP14AaABAQ'));
  }).done();

}).call(this);
